# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/itzg/minecraft-server:latest"
  amd64: "ghcr.io/itzg/minecraft-server:latest"
  armv7: "ghcr.io/itzg/minecraft-server:latest"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Minecreaft Server Java Edition"
  org.opencontainers.image.description: "Dedicated Server for Minecraft Java Edition"
  org.opencontainers.image.source: "https://github.com/ruthem/HA-addons"
  org.opencontainers.image.licenses: "Apache License 2.0"
args:
  TEMPIO_VERSION: "2021.09.0"
