# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Example add-on
version: "0.0.1"
slug: minecraft-server
description: Minecraft Server Java Edition
url: "https://github.com/home-assistant/addons-example/tree/main/example"
arch:
  - amd64
init: false
map:
  - share:rw
options:
  message: "Hello world..."
schema:
  message: "str?"
#image: "ghcr.io/home-assistant/{arch}-addon-example"
