# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Minecraft Server
version: "0.0.2"
slug: minecraft-server
description: Minecraft Dedicated Server Java Edition
url: "https://github.com/ruthem/HA-addons/tree/main/minecraft-server"
arch:
  - amd64
init: false
ports:
  25565/tcp: 25565
ports_description:
  25565/tcp: Minecraft Port
map:
  - addons:rw
options:
  message: "Hello world..."
  eula: false
schema:
  message: "str?"
  eula: "bool"
#image: "ghcr.io/home-assistant/{arch}-addon-example"
